# Generated by Django 5.0.4 on 2024-04-16 02:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Nombre de categoria')),
                ('description', models.CharField(max_length=500, verbose_name='Descripción de categoria')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
            ],
            options={
                'verbose_name': 'Categoria de producto',
                'verbose_name_plural': 'Categorias de productos',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Finca',
            fields=[
                ('owner_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='Nombre del dueño')),
                ('name', models.CharField(max_length=250, verbose_name='Nombre de mi finca')),
                ('size_fina', models.PositiveIntegerField(verbose_name='Tamaño de finca (m2)')),
                ('latitud', models.DecimalField(decimal_places=10, max_digits=50, verbose_name='Latitud')),
                ('longitud', models.DecimalField(decimal_places=10, max_digits=50, verbose_name='Longitud')),
                ('num_trees_grown', models.PositiveIntegerField(verbose_name='Cantidad de árboles cultivados')),
                ('age_trees', models.PositiveIntegerField(verbose_name='Edad de árboles (años)')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
            ],
            options={
                'verbose_name': 'Mi finca',
                'verbose_name_plural': 'Mi finca',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Nombre del producto')),
                ('composition', models.CharField(max_length=2000, null=True, verbose_name='Descripción del producto')),
                ('due_date', models.DateTimeField(null=True, verbose_name='Fecha de vencimiento')),
                ('unit_value', models.IntegerField(default=0, verbose_name='Valor unitario del producto')),
                ('purchased_amount', models.IntegerField(default=0, verbose_name='Cantidad de producto comprado')),
                ('quantity_consumed', models.IntegerField(default=0, verbose_name='Cantidad de producto consumido')),
                ('quantity_stock', models.IntegerField(default=0, verbose_name='Cantidad de producto en inventario')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.categoryproduct', verbose_name='Tipo de producto')),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.finca', verbose_name='Nombre de la finca')),
            ],
            options={
                'verbose_name': 'Inventario de producto',
                'verbose_name_plural': 'Inventario de productos',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='CultivationNovelty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('harvest', models.PositiveIntegerField(verbose_name='Cantidad de cosecha (kg)')),
                ('irrigation', models.PositiveIntegerField(verbose_name='Cantidad de riego (mm)')),
                ('fertilizer', models.PositiveIntegerField(verbose_name='Cantidad de abono (g)')),
                ('pruning', models.BooleanField(verbose_name='¿Podó?')),
                ('pest_control', models.BooleanField(verbose_name='¿Realizó control de plagas?')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.finca', verbose_name='Nombre de la finca')),
                ('inventory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='farmer.inventory', verbose_name='Producto de abono')),
            ],
            options={
                'verbose_name': 'Novedad de cultivo',
                'verbose_name_plural': 'Novedades de cultivos',
                'ordering': ['-created'],
            },
        ),
    ]
