# Generated by Django 5.0.2 on 2024-03-28 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cultivationnovelty',
            name='pest_control',
            field=models.BooleanField(verbose_name='¿Realiza control de plagas?'),
        ),
        migrations.AlterField(
            model_name='cultivationnovelty',
            name='pruning',
            field=models.BooleanField(verbose_name='¿Podó?'),
        ),
    ]
