# Generated by Django 5.0.2 on 2024-03-28 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0002_alter_cultivationnovelty_pest_control_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='due_date',
            field=models.DateTimeField(verbose_name='Fecha de vencimiento'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='purchased_amount',
            field=models.IntegerField(default=0, verbose_name='Cantidad de producto comprado'),
        ),
    ]
