# Generated by Django 5.0.2 on 2024-03-29 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0004_alter_inventory_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finca',
            name='latitud',
            field=models.DecimalField(decimal_places=10, max_digits=10, verbose_name='Latitud'),
        ),
        migrations.AlterField(
            model_name='finca',
            name='longitud',
            field=models.DecimalField(decimal_places=10, max_digits=10, verbose_name='Longitud'),
        ),
    ]
