# Generated by Django 5.0.2 on 2024-03-29 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0005_alter_finca_latitud_alter_finca_longitud'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finca',
            name='latitud',
            field=models.DecimalField(decimal_places=10, max_digits=50, verbose_name='Latitud'),
        ),
        migrations.AlterField(
            model_name='finca',
            name='longitud',
            field=models.DecimalField(decimal_places=10, max_digits=50, verbose_name='Longitud'),
        ),
    ]
