# Generated by Django 5.0.2 on 2024-04-01 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0006_alter_finca_latitud_alter_finca_longitud'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='number_lote',
        ),
        migrations.AlterField(
            model_name='cultivationnovelty',
            name='fertilizer',
            field=models.PositiveIntegerField(verbose_name='Cantidad de abono (g)'),
        ),
        migrations.AlterField(
            model_name='cultivationnovelty',
            name='harvest',
            field=models.PositiveIntegerField(verbose_name='Cantidad de cosecha (kg)'),
        ),
        migrations.AlterField(
            model_name='cultivationnovelty',
            name='irrigation',
            field=models.PositiveIntegerField(verbose_name='Cantidad de riego (mm)'),
        ),
        migrations.AlterField(
            model_name='cultivationnovelty',
            name='pest_control',
            field=models.BooleanField(verbose_name='¿Realizó control de plagas?'),
        ),
    ]
