# Generated by Django 5.0.2 on 2024-04-02 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0007_remove_inventory_number_lote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cultivationnovelty',
            name='inventario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='farmer.inventory', verbose_name='Prodcuto de abono'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='composition',
            field=models.CharField(max_length=2000, null=True, verbose_name='Descripción del producto'),
        ),
    ]
