# Generated by Django 5.0.2 on 2024-04-02 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0008_cultivationnovelty_inventario_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cultivationnovelty',
            old_name='inventario',
            new_name='inventory',
        ),
    ]
