# Generated by Django 5.0.4 on 2024-07-15 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farmer', '0001_initial'),
        ('researcher', '0007_alter_apiparametersfinca_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIParameterNasaFinca',
            fields=[
                ('finca', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='farmer.finca', verbose_name='Nombre de la finca')),
                ('latitud', models.DecimalField(decimal_places=10, max_digits=50, verbose_name='Latitud')),
                ('longitud', models.DecimalField(decimal_places=10, max_digits=50, verbose_name='Longitud')),
                ('date_exceute', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de ejecución')),
                ('date_start', models.DateTimeField(verbose_name='Fecha de inicio para exportación de datos')),
                ('date_end', models.DateTimeField(verbose_name='Fecha de fin para exportación de datos')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
            ],
            options={
                'verbose_name': 'Parametros Api (climatológica)',
                'verbose_name_plural': 'Parametros Api (climatologica)',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='DataApiNasaFinca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(max_length=50, verbose_name='Date en formato YYYY-MM-DD')),
                ('allsky_sfc_sw_dwn', models.DecimalField(decimal_places=2, max_digits=50, verbose_name='ALLSKY_SFC_SW_DWN')),
                ('clrsky_sfc_sw_dwn', models.DecimalField(decimal_places=2, max_digits=50, verbose_name='CLRSKY_SFC_SW_DWN')),
                ('t2m_max', models.DecimalField(decimal_places=2, max_digits=50, verbose_name='T2M_MAX')),
                ('t2m_min', models.DecimalField(decimal_places=2, max_digits=50, verbose_name='T2M_MIN')),
                ('t2mdew', models.DecimalField(decimal_places=2, max_digits=50, verbose_name='T2MDEW')),
                ('prectotcorr', models.DecimalField(decimal_places=2, max_digits=50, verbose_name='PRECTOTCORR')),
                ('rh2m', models.DecimalField(decimal_places=2, max_digits=50, verbose_name='RH2M')),
                ('ws2m', models.DecimalField(decimal_places=2, max_digits=50, verbose_name='WS2M')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('api_parameters_finca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='agricultural_engineer.apiparameternasafinca', verbose_name='Parametros API de finca')),
            ],
            options={
                'verbose_name': 'Datos climatilogicos de la finca',
                'verbose_name_plural': 'Datos climatilogicos de la fincas',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='DataApiNasaImputation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date en formato YYYY-MM-DD')),
                ('allsky_sfc_sw_dwn', models.DecimalField(decimal_places=2, max_digits=50, verbose_name='ALLSKY_SFC_SW_DWN')),
                ('clrsky_sfc_sw_dwn', models.DecimalField(decimal_places=2, max_digits=50, verbose_name='CLRSKY_SFC_SW_DWN')),
                ('t2m_max', models.DecimalField(decimal_places=2, max_digits=50, verbose_name='T2M_MAX')),
                ('t2m_min', models.DecimalField(decimal_places=2, max_digits=50, verbose_name='T2M_MIN')),
                ('t2mdew', models.DecimalField(decimal_places=2, max_digits=50, verbose_name='T2MDEW')),
                ('prectotcorr', models.DecimalField(decimal_places=2, max_digits=50, verbose_name='PRECTOTCORR')),
                ('rh2m', models.DecimalField(decimal_places=2, max_digits=50, verbose_name='RH2M')),
                ('ws2m', models.DecimalField(decimal_places=2, max_digits=50, verbose_name='WS2M')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('api_parameters_finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agricultural_engineer.apiparameternasafinca', verbose_name='Datos de la finca')),
                ('type_imp_data', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='researcher.typeimpfielddataclima', verbose_name='Tipo de imputación')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
