# Generated by Django 5.0.4 on 2024-07-17 04:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agricultural_engineer', '0001_initial'),
        ('farmer', '0001_initial'),
        ('researcher', '0007_alter_apiparametersfinca_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataapinasafinca',
            options={'ordering': ['date'], 'verbose_name': 'Datos climatilogicos de la finca', 'verbose_name_plural': 'Datos climatilogicos de las fincas'},
        ),
        migrations.AlterField(
            model_name='apiparameternasafinca',
            name='finca',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='farmer.finca', verbose_name='Selección de finca'),
        ),
        migrations.CreateModel(
            name='PronosticModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_model', models.BinaryField()),
                ('power', models.DecimalField(decimal_places=10, max_digits=50, verbose_name='power')),
                ('mean', models.DecimalField(decimal_places=10, max_digits=50, verbose_name='mean')),
                ('st_d', models.DecimalField(decimal_places=10, max_digits=50, verbose_name='st_d')),
                ('data_forecasts', models.TextField()),
                ('final_columns', models.TextField()),
                ('final_probs', models.TextField()),
                ('Irrigation_and_drainage', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('columns_api_nasa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='researcher.columnsapinasa', verbose_name='Columna a analizar')),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.finca', verbose_name='Nombre de la finca')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
