# Generated by Django 5.0.4 on 2024-07-23 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agricultural_engineer', '0002_alter_dataapinasafinca_options_and_more'),
        ('farmer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BeastPronosticModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(max_length=4, verbose_name='Día')),
                ('allsky_sfc_sw_dwn', models.DecimalField(decimal_places=2, max_digits=50, verbose_name='ALLSKY_SFC_SW_DWN')),
                ('clrsky_sfc_sw_dwn', models.DecimalField(decimal_places=2, max_digits=50, verbose_name='CLRSKY_SFC_SW_DWN')),
                ('t2m_max', models.DecimalField(decimal_places=2, max_digits=50, verbose_name='T2M_MAX')),
                ('t2m_min', models.DecimalField(decimal_places=2, max_digits=50, verbose_name='T2M_MIN')),
                ('t2mdew', models.DecimalField(decimal_places=2, max_digits=50, verbose_name='T2MDEW')),
                ('prectotcorr', models.DecimalField(decimal_places=2, max_digits=50, verbose_name='PRECTOTCORR')),
                ('rh2m', models.DecimalField(decimal_places=2, max_digits=50, verbose_name='RH2M')),
                ('ws2m', models.DecimalField(decimal_places=2, max_digits=50, verbose_name='WS2M')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.finca', verbose_name='Nombre de la finca')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
