# Generated by Django 5.0.4 on 2024-07-23 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agricultural_engineer', '0003_beastpronosticmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beastpronosticmodel',
            name='allsky_sfc_sw_dwn',
            field=models.DecimalField(decimal_places=2, max_digits=50, null=True, verbose_name='ALLSKY_SFC_SW_DWN'),
        ),
        migrations.AlterField(
            model_name='beastpronosticmodel',
            name='clrsky_sfc_sw_dwn',
            field=models.DecimalField(decimal_places=2, max_digits=50, null=True, verbose_name='CLRSKY_SFC_SW_DWN'),
        ),
        migrations.AlterField(
            model_name='beastpronosticmodel',
            name='prectotcorr',
            field=models.DecimalField(decimal_places=2, max_digits=50, null=True, verbose_name='PRECTOTCORR'),
        ),
        migrations.AlterField(
            model_name='beastpronosticmodel',
            name='rh2m',
            field=models.DecimalField(decimal_places=2, max_digits=50, null=True, verbose_name='RH2M'),
        ),
        migrations.AlterField(
            model_name='beastpronosticmodel',
            name='t2m_max',
            field=models.DecimalField(decimal_places=2, max_digits=50, null=True, verbose_name='T2M_MAX'),
        ),
        migrations.AlterField(
            model_name='beastpronosticmodel',
            name='t2m_min',
            field=models.DecimalField(decimal_places=2, max_digits=50, null=True, verbose_name='T2M_MIN'),
        ),
        migrations.AlterField(
            model_name='beastpronosticmodel',
            name='t2mdew',
            field=models.DecimalField(decimal_places=2, max_digits=50, null=True, verbose_name='T2MDEW'),
        ),
        migrations.AlterField(
            model_name='beastpronosticmodel',
            name='ws2m',
            field=models.DecimalField(decimal_places=2, max_digits=50, null=True, verbose_name='WS2M'),
        ),
    ]
