# Generated by Django 5.0.4 on 2024-08-18 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agricultural_engineer', '0004_alter_beastpronosticmodel_allsky_sfc_sw_dwn_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='beastpronosticmodel',
            name='prectotcorr',
        ),
        migrations.AddField(
            model_name='beastpronosticmodel',
            name='prectotcorr1',
            field=models.DecimalField(decimal_places=2, max_digits=50, null=True, verbose_name='PRECTOTCORR_1'),
        ),
        migrations.AddField(
            model_name='beastpronosticmodel',
            name='prectotcorr2',
            field=models.DecimalField(decimal_places=2, max_digits=50, null=True, verbose_name='PRECTOTCORR_2'),
        ),
        migrations.AddField(
            model_name='beastpronosticmodel',
            name='prectotcorr3',
            field=models.DecimalField(decimal_places=2, max_digits=50, null=True, verbose_name='PRECTOTCORR_3'),
        ),
    ]
