# Generated by Django 5.0.4 on 2024-09-15 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agricultural_engineer', '0006_twostagefincamodel'),
        ('researcher', '0007_alter_apiparametersfinca_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataapinasaimputation',
            name='type_imp_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='researcher.typeimpfielddataclima', verbose_name='Tipo de imputación'),
        ),
    ]
