# Generated by Django 5.0.4 on 2024-07-10 13:54

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researcher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forecastscenarios',
            name='finca',
        ),
        migrations.AddField(
            model_name='forecastscenarios',
            name='cod_modelo_iter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='researcher.iterativemodelling', verbose_name='Modelo iterativo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='forecastscenarios',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='iterativemodelling',
            name='contamination',
            field=models.DecimalField(decimal_places=1, default=0.1, max_digits=1, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Contaminación'),
        ),
    ]
