# Generated by Django 5.0.4 on 2024-07-12 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmer', '0001_initial'),
        ('researcher', '0003_remove_mergescenarios_finca_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwoStageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='farmer.finca', verbose_name='Nombre de la finca')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
