# Generated by Django 5.0.4 on 2024-07-15 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('researcher', '0005_twostagemodel_irrigation_and_drainage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iterativemodelling',
            name='columns_api_nasa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='researcher.columnsapinasa', verbose_name='Columna a analizar'),
        ),
    ]
