# Generated by Django 5.0.4 on 2024-07-15 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('researcher', '0006_alter_iterativemodelling_columns_api_nasa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apiparametersfinca',
            options={'ordering': ['-created'], 'verbose_name': 'Parametros Api (climatológica)', 'verbose_name_plural': 'Parametros Api (climatológica)'},
        ),
    ]
